name: Serverless Workshop CI/CD
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  integration-test:
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          - node-version: 16
          - cache: 'npm'
      - name: Install dependencies
        run: npm ci # use ci command b/c it's safer 
      - name: Run integration tests
        run: npm run test
